- package-lock.json
- package.json
- src/App.js
- src/components/login/LoginForm.css
- src/components/login/LoginForm.js
**changes:**
added the login component, and the initial CSS
**issues:**
fixes issue #1 
**screenshots**
> Feature login page

- .vscode/settings.json
- package-lock.json
- package.json
- public/keycloak.json
- public/silent-check-sso.html
- src/App.js
- src/components/loading/Loading.js
- src/components/login/LoginForm.js
- src/const/roles.js
- src/index.js
- src/keycloak.js
- src/keycloak.json
- src/pages/StartPage.js
- src/routes/KeycloakRoute.jsx
Keycloak is setup. There will be conflicts.
#8
> Keycloak setup

- package-lock.json
- public/keycloak.json
added keycloak server with cloud IAM, so changed URL to: https://lemur-3.cloud-iam.com/auth/
> keycloak setup with cloud-iam

- src/components/navbar/Navbar.js
- src/pages/StartPage.js
> added header to display and added login/logout

- src/App.js
- src/components/navbar/Navbar.js
- src/keycloak.js
- src/keycloak.json
- src/pages/StartPage.js
functions that change the redirectURI before
so that it properly redirects to "/profile" after
logging in and "/" when logging out.
> put keycloak.login() and keycloak.logout() into

- src/App.js
- src/components/profile/ProfileHeader.css
- src/components/profile/ProfileHeader.js
- src/pages/Profile.js
**Changes:**
Created the "ProfileHeader" component since the header should look different from start page header. The user is greeted with their name which is fetched dynamically.
**Issues:**
fixes first task of issue #13
**Screenshots:**
> created header and greets user with name dynamically

- src/App.js
- src/components/navbar/AuthMenu.css
- src/components/navbar/MenuItems.css
- src/components/navbar/MenuItems.js
- src/components/navbar/Navbar.js
- src/components/profile/ProfileHeader.css
- src/components/profile/ProfileHeader.js
- src/components/profile/ProfileTabs.css
- src/components/profile/ProfileTabs.js
- src/components/programs/ProgramsList.js
- src/index.css
- src/keycloak.js
- src/pages/Profile.css
- src/pages/Profile.js
- src/pages/StartPage.css
- src/pages/StartPage.js
**Changes:**
Refactored a lot of CSS since the previous CSS files used HTML elements as CSS selectors which is not specific enough when targeting elements. Therefore a lot of CSS classes was added to almost every JSX/HTML element.
**Issues:**
**Screenshots:**
The StarterPage:
The Profile page:
> huge CSS refactor

- src/pages/Dashboard.js
- src/pages/Goals.js
- src/pages/Programs.js
- src/pages/Workouts.js
- src/pages/profile/ProfileHeader.js
- src/pages/profile/ProfileTabs.css
- src/pages/profile/ProfileTabs.js
**Changes:**
Used the "active" class in the NavLink component from react-router to underline the current active URL path.
**Issues:**
Fixes #20
> active link feedback

- package-lock.json
- package.json
- src/App.js
- src/components/Calendar.css
- src/components/CalendarPlan.js
- src/components/loading/Loading.css
- src/components/loading/Loading.js
- src/components/navbar/Greeting.js
- src/index.js
- src/pages/profile/Profile.css
- src/pages/profile/Profile.js
- src/pages/profile/ProfileHeader.js
Implemented a calendar to the dashboard, and started working on a custom loading screen during login and logout
> React Calendar

- src/components/programs/Program.css
- src/components/programs/Program.js
**Changes:**
Created the layout for the program details page.
**Issues:**
related to #7 
**Screenshots:**
> program details page

- src/App.js
- src/components/workouts/Workout.js
- src/components/workouts/WorkoutsList.js
- src/pages/Workouts.css
- src/pages/Workouts.js
**Changes:**
Added Workout components in order to view all workouts and details for a single workout with information about an exercise
**Isuues:**
related to #26 
**Screenshots:**
All workouts:
A single workout with details about the exercises:
> workout details

- package-lock.json
- package.json
- src/App.js
- src/components/navbar/Navbar.css
- src/components/navbar/Navbar.js
- src/const/roles.js
> authenticated urls and mefit in the middle links

- src/App.js
- src/api/fetchProgramData.js
- src/api/fetchWorkoutData.js
- src/components/programs/Program.js
- src/components/programs/ProgramsList.js
- src/pages/Programs.js
**changes:**
The frontend now reaches out to API endpoints "api/v1/programs" to fetch all stored programs, and "api/v1/programs/{id}" to fetch specific program.
> fetch all programs, and one program

- src/api/fetchProgramData.js
- src/components/workout/WorkoutsList.js
Added JWT token to request headers
> JWT token in request headers

- src/App.js
- src/pages/SignUpForm.css
- src/pages/SignUpForm.js
**changes:**
added signup form for the user to POST data to db
> Signup form

- src/App.js
- src/api/syncDbWithKeycloak.js
- src/components/navbar/AuthMenu.js
- src/pages/AdminPage.js
- src/pages/SignUpForm.js
> new admin page button and link to profile for

- src/App.js
- src/api/fetchUserData.js
- src/components/goals/ActiveGoalsList.js
- src/components/goals/CompletedGoalsList.js
- src/components/goals/GoalFormModal.css
- src/components/goals/GoalFormModal.js
- src/components/goals/GoalSelect.css
- src/components/goals/GoalSelect.js
- src/components/goals/LogActivityModal.js
- src/components/programs/SelectProgram.js
- src/pages/SignUpInfo.css
- src/pages/SignUpInfo.js
**Changes:**
The GoalFormModal fetches current stored programs and when the user selects a start date it automatically sets the end date to 7 days ahead.
> added select dropdown to CreateFormModal

- src/api/fetchGoals.js
- src/api/postGoal.js
- src/components/goals/ActiveGoalsList.js
**Changes:**
Created the fetchGoals function that will fetch all goals from the API and display them to the user on the "goals" page.
**screenshots:**
> Fetching Goals

- src/api/postGoal.js
- src/components/programs/Program.js
fetching workouts related to a specific program
> fetching workouts related to a specific program

- src/api/fetchGoals.js
- src/api/postGoal.js
**changes:**
Changed the postGoal() to POST the userI D, and changed t fetchGoals() function to only fetch the goals of the logged in user.
> fetch and post goals

- public/keycloak.json
- src/api/contribute.js
- src/components/programs/ProgramForm.js
- src/components/workout/WorkoutForm.js
> create program works together with spring

- src/components/programs/ProgramForm.js
- src/components/progressBar/ProgressBar.js
- src/pages/Profile.css
- src/pages/Profile.js
added form input for image URL
> added form input for image URL
